### ISSUE TITLE
OCaml syntax highlighting

### ISSUE THREAD

**Issue by trefis** [mmottl/vim-files#1]
I feel a bit stupid opening an issue in someone's _vim-files_ repository, but since people started using your `.vim/syntax/ocaml.vim` it's probably the best place (it's not distributed by vim, but it is included in projects like https://github.com/rgrinberg/vim-ocaml ).

Here is a piece of syntax which is not properly handled: `include (struct`.
You can get completely weird results when you start writing things like:

``` ocaml
include (struct
  let x = ") lolol"
  let y = 3
end)
```

While I am at it, here is another problem I have in `.mli` files: the presence of a comment following an include completely disturbs the highlighting.
Here is a minimal example:

``` ocaml
include M
(* some comment *)
val x : typ
```

These look like "minor" (hm hm) problems, but I have tried to modify vim syntax files in the past, and I do not dare to try it again.

If it's not too much trouble, I would really appreciate it if you could take care of these issues.

Cheers.

**Comment by mmottl** [comment]
You can avoid the first issue by dropping the parentheses around the `struct` block.  I've just added a small "fix" for the second issue.  Vim syntax files are enormously brittle and hard to understand.  It's well possible that this fix will introduce issues elsewhere.

**Comment by rgrinberg** [comment]
@trefis I've applied the "fix" to vim-ocaml as well.

Thanks @mmottl !

**Comment by trefis** [comment]
> Vim syntax files are enormously brittle and hard to understand. It's well possible that this fix will introduce issues elsewhere.

Yes, I understand.

Thanks!
